### ISSUE TITLE
no messages receive

### ISSUE THREAD

**Issue by petrk94** [stephenlb/angularjs-chat#10]
Hello @stephenlb ,

I wanted to use the application in a team of 20 persons,
but in a test with 3 persons, I needed to realize, that no all of us are receiving the messages, I have send over the tutorial angularjs chat app (this one with the nice design)
The keys from Pubnup are inserted and thats working, but well, not all get the messages.
We are using chrome, because IE and Firefox are not displaying it correctly.

Hope for a answer

**Comment by stephenlb** [comment]
Send your code in a URL, and we can test it out!

**Comment by petrk94** [comment]
Hello,
thanks for your fast answer, the issue is solved, the Chrome still had the wrong pub/subcribe key in the cache. a reload the page over the developer tools with disabled cache, solved the problem.
