### ISSUE TITLE
Should i use any server-side backend?

### ISSUE THREAD

**Issue by LightVolk** [stephenlb/angularjs-chat#13]
Should i use any server-side backend?

I want to write simple chat with Steam friends via Angular. So, should  write any server app or  can use only this chat (+steamapi)?

**Comment by stephenlb** [comment]
For server/streamapi access I recommend you checkout [ChatEngine](https://github.com/pubnub/chat-engine).  It allows you to better integrate components.

**Comment by stephenlb** [comment]
You may also be interested in [the AngularJS SDK](https://github.com/pubnub/pubnub-angular) 

![PubNub AngularJS](https://camo.githubusercontent.com/8cdf8e50d5b435348a5cf89147d91e1639bc3ce0/687474703a2f2f636c2e6c792f3234314e30713250327132322f53637265656e25323053686f74253230323031362d30322d30332532306174253230352e33322e3332253230504d2e706e67)

**Comment by LightVolk** [comment]
Thank you!
