### ISSUE TITLE
Understanding uuid()

### ISSUE THREAD

**Issue by ghost** [stephenlb/angularjs-chat#3]
Hi Stephen, could you please explain the significance of `c == 'x' ? r : (r & 0x3 | 0x8);` in case of `c != 'x'`?

Also, why have you used `4` and `y`?

**Comment by stephenlb** [comment]
I donno good question!  This is just a ternary that increases histogram spread reducing the likelihood of generating a collision.

**Comment by stephenlb** [comment]
It is best to not use `uuid()` method and instead set your own user IDs based on your DB.  But UUID is a good placeholder as a temporary User ID.

**Comment by stephenlb** [comment]
let me know if this helps!
